spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  mail:
    host: 'sandbox.smtp.mailtrap.io'
    port: 587
    properties:
      mail:
        debug: true
      smtp:
        auth: true
        starttls:
          enable: true
    username: ed7fa305304316
    password: cc743f0701049f
  freemarker:
    template-loader-path: 'classpath:/templates'
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: test
      name: test-yaml
      environment: testing
      enabled: false
      servers:
        - www.abc.test.com
        - www.xyz.test.com
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password: user
    url: jdbc:h2:mem:~
  sql:
    init:
      mode: always
---
server:
  port: 9090
spring:
  config:
    activate:
      on-profile: dev
      name: dev-yaml
      environment: development
      enabled: true
      servers:
        - www.abc.com
        - www.xyz.com
  datasource:
    url: jdbc:postgresql://localhost:5432/orm_task
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
